import{i as p,S as b,a as v}from"./assets/vendor-5401a4b0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const a of document.querySelectorAll('link[rel="modulepreload"]'))r(a);new MutationObserver(a=>{for(const o of a)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function n(a){const o={};return a.integrity&&(o.integrity=a.integrity),a.referrerPolicy&&(o.referrerPolicy=a.referrerPolicy),a.crossOrigin==="use-credentials"?o.credentials="include":a.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(a){if(a.ep)return;a.ep=!0;const o=n(a);fetch(a.href,o)}})();const l=document.querySelector(".gallery"),C=document.getElementById("loader"),E=document.getElementById("search-form"),L=document.getElementById("load-more"),I=document.getElementById("loading-indicator"),B="42175181-9f2e4ea0c75ffabf50c3ef9f9";let c=1,w="",$=0,S=0;function R(e){p.success({title:"Success",message:e,position:"topRight"})}function m(e){p.error({title:"Error",message:e,position:"topRight"})}function d(e){L.style.display=e?"block":"none"}function u(e){C.style.display=e?"block":"none",I.style.display=e?"block":"none"}async function q(e,t=1){const n=`https://pixabay.com/api/?key=${B}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=15`;try{const r=await v.get(n);return S=r.data.totalHits,r.data.hits}catch(r){throw m("Failed to fetch images."),r}}async function x(){const e=l.querySelector(".image-card").getBoundingClientRect().height;window.scrollBy({top:2*e,left:0,behavior:"smooth"})}async function y(e,t){try{u(!0);const n=await q(e,t);n.length>0?(t===1?H(n):M(n),R(`Was found: ${n.length} images`),P(),n.length<15?(m("We are sorry, but you have reached the end of search results."),d(!1)):d(!0),x()):(l.innerHTML="",m(`Sorry, there are no images matching your search query "${e}". Please try again!`),d(!1))}finally{u(!1)}}E.addEventListener("submit",async function(e){e.preventDefault(),d(!1);const t=document.getElementById("query").value.trim();if(!t){p.warning({title:"Warning",message:"Please enter a search query."});return}w=t,c=1,t.toLowerCase()==="batman car"?await y(t,c):await y(t,c)});L.addEventListener("click",async function(){try{u(!0),c++,await y(w,c)}catch{m("Failed to fetch additional images.")}finally{u(!1)}});function H(e){l.innerHTML="";const t=document.createDocumentFragment();e.forEach(n=>{const{largeImageURL:r,webformatURL:a,tags:o,likes:s,views:f,comments:g,downloads:h}=n,i=document.createElement("div");i.classList.add("image-card"),i.innerHTML=`
            <a href="${r}" data-lightbox="image-set" data-title="${o}">
                <img src="${a}" alt="${o}">
                <div class="info">Likes: ${s}, Views: ${f}, Comments: ${g}, Downloads: ${h}</div>
            </a>
        `,t.appendChild(i)}),l.appendChild(t),$+=e.length}function M(e){const t=document.createDocumentFragment();e.forEach(n=>{const{largeImageURL:r,webformatURL:a,tags:o,likes:s,views:f,comments:g,downloads:h}=n,i=document.createElement("div");i.classList.add("image-card"),i.innerHTML=`
            <a href="${r}" data-lightbox="image-set" data-title="${o}">
                <img src="${a}" alt="${o}">
                <div class="info">Likes: ${s}, Views: ${f}, Comments: ${g}, Downloads: ${h}</div>
            </a>
        `,t.appendChild(i)}),l.appendChild(t),$+=e.length}function P(){new b(".gallery a").refresh()}
//# sourceMappingURL=commonHelpers.js.map
