import{i as p,S as b,a as v}from"./assets/vendor-5401a4b0.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const s of n.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function r(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();const l=document.querySelector(".gallery"),C=document.getElementById("loader"),E=document.getElementById("search-form"),$=document.getElementById("load-more"),I=document.getElementById("loading-indicator"),B="42175181-9f2e4ea0c75ffabf50c3ef9f9";let c=1,L="",w=0,S=0;function q(e){p.success({title:"Success",message:e,position:"topRight"})}function m(e){p.error({title:"Error",message:e,position:"topRight"})}function d(e){$.style.display=e?"block":"none"}function u(e){C.style.display=e?"block":"none",I.style.display=e?"block":"none"}async function R(e,a=1){const o={key:B,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15},r=`https://pixabay.com/api/?key=${o.key}&q=${encodeURIComponent(e)}&image_type=${o.image_type}&orientation=${o.orientation}&safesearch=${o.safesearch}&page=${a}&per_page=${o.per_page}`;try{const t=await v.get(r);return S=t.data.totalHits,t.data.hits}catch(t){throw m("Failed to fetch images."),t}}async function x(){const e=l.querySelector(".image-card").getBoundingClientRect().height;window.scrollBy({top:2*e,left:0,behavior:"smooth"})}async function h(e,a){try{u(!0),c=1;const o=await R(e,a);o.length>0?(a===1?H(o):M(o),q(`Was found: ${o.length} images`),P(),o.length<15?(m("We are sorry, but you have reached the end of search results."),d(!1)):d(!0),x()):(l.innerHTML="",m(`Sorry, there are no images matching your search query "${e}". Please try again!`),d(!1))}finally{u(!1)}}E.addEventListener("submit",async function(e){e.preventDefault(),d(!1);const a=document.getElementById("query").value.trim();if(!a){p.warning({title:"Warning",message:"Please enter a search query."});return}L=a,c=1,a.toLowerCase()==="batman car"?await h(a,c):await h(a,c)});$.addEventListener("click",async function(){try{u(!0),c++,await h(L,c)}catch{m("Failed to fetch additional images.")}finally{u(!1)}});function H(e){l.innerHTML="";const a=document.createDocumentFragment();e.forEach(o=>{const{largeImageURL:r,webformatURL:t,tags:n,likes:s,views:f,comments:g,downloads:y}=o,i=document.createElement("div");i.classList.add("image-card"),i.innerHTML=`
            <a href="${r}" data-lightbox="image-set" data-title="${n}">
                <img src="${t}" alt="${n}">
                <div class="info">Likes: ${s}, Views: ${f}, Comments: ${g}, Downloads: ${y}</div>
            </a>
        `,a.appendChild(i)}),l.appendChild(a),w+=e.length}function M(e){const a=document.createDocumentFragment();e.forEach(o=>{const{largeImageURL:r,webformatURL:t,tags:n,likes:s,views:f,comments:g,downloads:y}=o,i=document.createElement("div");i.classList.add("image-card"),i.innerHTML=`
            <a href="${r}" data-lightbox="image-set" data-title="${n}">
                <img src="${t}" alt="${n}">
                <div class="info">Likes: ${s}, Views: ${f}, Comments: ${g}, Downloads: ${y}</div>
            </a>
        `,a.appendChild(i)}),l.appendChild(a),w+=e.length}function P(){new b(".gallery a").refresh()}
//# sourceMappingURL=commonHelpers.js.map
